from __future__ import annotations

from .models import SlashCommand, SlashTargetId


GENERATED_MARKER = "<!-- Generated by Slash Command Manager. Do not edit manually. -->"


def render_slash_command(command: SlashCommand, target: SlashTargetId) -> str:
    if target == "cursor":
        return _render_cursor(command)
    return _render_frontmatter(command)


def is_generated_document(content: str) -> bool:
    return GENERATED_MARKER in content


def parse_slash_command_document(name: str, content: str, target: SlashTargetId) -> SlashCommand:
    if target == "cursor":
        return _parse_cursor_document(name, content)
    return _parse_frontmatter_document(name, content)


def _render_frontmatter(command: SlashCommand) -> str:
    return "\n".join(
        [
            "---",
            f"description: {_quote_frontmatter(command.description)}",
            "---",
            "",
            command.prompt.rstrip(),
            "",
        ]
    )


def _render_cursor(command: SlashCommand) -> str:
    return "\n".join(
        [
            f"{command.description.rstrip()}",
            "",
            command.prompt.rstrip(),
            "",
        ]
    )


def _quote_frontmatter(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _parse_frontmatter_document(name: str, content: str) -> SlashCommand:
    description = ""
    body = content
    lines = content.splitlines()
    if lines[:1] == ["---"]:
        metadata: dict[str, str] = {}
        index = 1
        while index < len(lines):
            line = lines[index]
            index += 1
            if line.strip() == "---":
                body = "\n".join(lines[index:]).strip()
                break
            if ":" not in line:
                continue
            key, value = line.split(":", 1)
            metadata[key.strip()] = _unquote_scalar(value.strip())
        description = metadata.get("description", "")
    prompt = _strip_legacy_marker(body).strip()
    return SlashCommand(name=name, description=description or name, prompt=prompt or body.strip())


def _parse_cursor_document(name: str, content: str) -> SlashCommand:
    body = _strip_legacy_marker(content).strip()
    parts = body.splitlines()
    description = ""
    prompt_lines = parts
    for index, line in enumerate(parts):
        if line.strip():
            description = line.strip()
            prompt_lines = parts[index + 1 :]
            break
    prompt = "\n".join(prompt_lines).strip()
    return SlashCommand(name=name, description=description or name, prompt=prompt or body)


def _strip_legacy_marker(content: str) -> str:
    return content.replace(GENERATED_MARKER, "").strip()


def _unquote_scalar(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1]
    return value


__all__ = [
    "GENERATED_MARKER",
    "is_generated_document",
    "parse_slash_command_document",
    "render_slash_command",
]
